pcaalg = prcomp(groupalg[2:66], scale. = T)
pcanon = prcomp(groupnon[2:65], scale. = T)
pcaran = prcomp(groupran[2:67], scale. = T)
pcaall = prcomp(groupall[2:66], scale. = T)
pca4 = prcomp(group4[2:67], scale. = T)
pca355 = prcomp(groupall[2:66], scale. = T)
pca300 = prcomp(group300[2:66], scale. = T)
pca1657 = prcomp(selepat1657[2:67], scale. = T)
pca10 = prcomp(group10[2:66], scale. = T)

library(factoextra)
fviz_contrib(pcajnon, choice = "var", axes = 1, top = 10)
fviz_contrib(pcajnon, choice = "var", axes = 2, top = 10)
fviz_pca_biplot(pcajnon, label="var", habillage = groupnon[,1], addEllipses = T, ellipse.level=0.95)

pcajran = prcomp(groupran[2:67], scale. = T)
fviz_contrib(pcajran, choice = "var", axes = 1, top = 10)
fviz_contrib(pcajran, choice = "var", axes = 2, top = 10)
fviz_pca_biplot(pcajran, label="var", habillage = groupran[,1], addEllipses = T, ellipse.level=0.95)